version: '3.9'

services:
  backend:
    volumes:
      - ./backend/python:/app
    environment:
      - ENVIRONMENT=development
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port ${BACKEND_PORT:-4000} --reload

  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_BACKEND_URL=http://localhost:${BACKEND_PORT:-4000}
    command: npm run dev -- --host

  speech-service:
    volumes:
      - ./speech-service:/app
    environment:
      - ENVIRONMENT=development
      - PYTHONUNBUFFERED=1

  vector-store:
    environment:
      - ENVIRONMENT=development 