version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: backend-python
    ports:
      - "${BACKEND_PORT:-4000}:${BACKEND_PORT:-4000}"
    env_file:
      - .env
    environment:
      - VECTOR_DB_URL=${VECTOR_DB_URL:-http://weaviate-db:8080}
      - AB_TEST_OPENAI_WEIGHT=0
      - AB_TEST_VECTOR_DB_WEIGHT=100
      - AB_TEST_LOCAL_LLM_WEIGHT=0
      - VECTOR_DB_CONFIDENCE_THRESHOLD=${VECTOR_DB_CONFIDENCE_THRESHOLD:-0.95}
    restart: unless-stopped
    depends_on:
      - vector-store-api
      - speech-service
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - BACKEND_URL=http://backend:${BACKEND_PORT:-4000}
      - VITE_VECTOR_STORE_URL=http://localhost:8082

  speech-service:
    build:
      context: ./speech-service
    container_name: speech-service
    ports:
      - "5005:5005"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./speech-service:/app

  weaviate-db:
    image: semitechnologies/weaviate:1.23.7
    container_name: weaviate-db
    ports:
      - "${WEAVIATE_PORT:-8081}:8080"
      - "50051:50051"
    restart: unless-stopped
    volumes:
      - weaviate_data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: ${VECTOR_DB_QUERY_LIMIT:-25}
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers'
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      CLUSTER_HOSTNAME: 'node1'
      GRPC_PORT: 50051
    depends_on:
      t2v-transformers:
        condition: service_healthy

  vector-store-api:
    build:
      context: ./vector-store
    ports:
      - "${VECTOR_STORE_PORT:-8082}:8082"
    env_file:
      - .env
    environment:
      - WEAVIATE_HOST=weaviate-db
      - WEAVIATE_PORT=8080
      - VECTOR_DB_URL=http://weaviate-db:8080
      - VECTOR_DB_CONFIDENCE_THRESHOLD=${VECTOR_DB_CONFIDENCE_THRESHOLD:-0.95}
    depends_on:
      - weaviate-db
    volumes:
      - ./vector-store:/app

  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-paraphrase-multilingual-MiniLM-L12-v2
    container_name: t2v-transformers
    environment:
      ENABLE_CUDA: '0'
      NVIDIA_VISIBLE_DEVICES: 'all'
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/.well-known/ready')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

networks:
  default:
    name: empathy-net

volumes:
  weaviate_data:
